#!/usr/bin/env python3

import libwyag
libwyag.main()

# This file is part of wyag <https://wyag.thb.lt>
# 
# Wyag is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation.
# 
# Wyag is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.
# 
# You should have received a copy of the GNU General Public License
# along with Wyag.  If not, see <https://www.gnu.org/licenses/>.